### ISSUE TITLE
Add project tagging so folks know what concepts have been covered

### ISSUE THREAD

**Issue by logankilpatrick** [logankilpatrick/Julia-Projects-for-Beginners#6]
We could add specific keywords after the exercise name which show it's tags / main ideas

**Comment by lilianabs** [comment]
Maybe we can use the tags from [Issue #7](https://github.com/logankilpatrick/Julia-Projects-for-Beginners/issues/7)? If you agree, then I can add them to the exercises :smile:

**Comment by logankilpatrick** [comment]
Done, thanks!
